### ISSUE TITLE
About another paper ConvRNN

### ISSUE THREAD

**Issue by xurutingtingting** [Lebo-Wang/cGCN_fMRI#1]
Hello, I don't know how to contact you. I am learning the processing of RNN on the brain Network. I have read one of your previous papers entitled Application of Convolutional Recurrent Neural Network for Individual Recognition Based on RBF Data, which impressed me a lot. I wonder if you could share your code with me, thank you very much

**Comment by leowang16** [comment]
> Hello, I don't know how to contact you. I am learning the processing of RNN on the brain Network. I have read one of your previous papers entitled Application of Convolutional Recurrent Neural Network for Individual Recognition Based on RBF Data, which impressed me a lot. I wonder if you could share your code with me, thank you very much

Please provide your contact info.

**Comment by xurutingtingting** [comment]
***@***.*** &nbsp; &nbsp;thank you very much!!!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lebo-Wang/cGCN_fMRI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lebo-Wang/cGCN_fMRI] About another paper ConvRNN (#1)





  
Hello, I don't know how to contact you. I am learning the processing of RNN on the brain Network. I have read one of your previous papers entitled Application of Convolutional Recurrent Neural Network for Individual Recognition Based on RBF Data, which impressed me a lot. I wonder if you could share your code with me, thank you very much
  
Please provide your contact info.

**Comment by xurutingtingting** [comment]
> > Hello, I don't know how to contact you. I am learning the processing of RNN on the brain Network. I have read one of your previous papers entitled Application of Convolutional Recurrent Neural Network for Individual Recognition Based on RBF Data, which impressed me a lot. I wonder if you could share your code with me, thank you very much
> 
> Please provide your contact info.

Hello, I am not sure if you have received my mail, so I will disturb you again. In addition, my email is 781945160@qq.com
