### ISSUE TITLE
About placeholder

### ISSUE THREAD

**Issue by Luoyunsong** [Lebo-Wang/cGCN_fMRI#2]
Hello, very nice work. But iI got a mistake called "module 'tensorflow' has no attribute 'placeholder'" on the colab notebook.The placeholder doesnt exist on the tf2.0.I don't know how to contact you. I am learning the GCN on the brain Network. I wonder if you could share your new code with me, thank you very much

**Comment by leowang16** [comment]
> Hello, very nice work. But iI got a mistake called "module 'tensorflow' has no attribute 'placeholder'" on the colab notebook.The placeholder doesnt exist on the tf2.0.I don't know how to contact you. I am learning the GCN on the brain Network. I wonder if you could share your new code with me, thank you very much

1. Original Colab notebook works for me.
2. I am not familiar with tf2.0, but it is recommended on tf1.x

**Comment by Luoyunsong** [comment]
My colab notebook can't load TF 1.4.0, I found this problem and reset TF. 1.14.0, finally it can run
