### ISSUE TITLE
Error in installing the dependencies.

### ISSUE THREAD

**Issue by uaadesh** [Lebo-Wang/cGCN_fMRI#3]
Hello,
I tried to run the colab notebook and it throws error in the first cell while installing the dependencies.
The same error occurs when I downloaded the code and tried to run it on my laptop:

ERROR: Could not find a version that satisfies the requirement tensorflow==1.4.1 (from versions: 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.5.1, 2.5.2, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2)
ERROR: No matching distribution found for tensorflow==1.4.1

I tried changing the version of tensorflow for installation but there are several incompatibility errors.

**Comment by leowang16** [comment]
try this at the beginning. I have not verified running everything, but it looks good to me.

> !pip install PyDrive
!pip install keras==2.1.5
!pip install tensorflow==1.13.1
!pip install h5py==2.8.0

**Comment by uaadesh** [comment]
Hey thank you it works now,
However I was trying to study the architecture of the model but in the notebook FC.npy is used to import the model:

model = get_model(
    graph_path='FC.npy', 
    ROI_N=ROI_N,
    frames=frames,
    kernels=[8,8,8,16,32,32], 
    k=k, 
    l2_reg=l2_reg, 
    dp=dp,
    num_classes=num_classes, 
    weight_path=None, 
    skip=[0,0])

can you tell me where should I look to study and experiment with the model?

**Comment by leowang16** [comment]
'model.py' or paper?
