### ISSUE TITLE
List index out of range error in ABIDE_leave_one_site_out.

### ISSUE THREAD

**Issue by uaadesh** [Lebo-Wang/cGCN_fMRI#4]
Hello,
I was trying to run the code for ABIDE_leave_one_site_out on Google Colab and there was an list index out of range error in the Get_model section of the code. I simply copied all the code in run_ABIDE_leave_one_site_out.py file on the colab notebook. 
Below is the Error.

IndexError                                Traceback (most recent call last)
<ipython-input-7-b2e782c23d20> in <module>()
     99       kernels=kernels,
    100       k=k, l2_reg=l2_reg,
--> 101       weight_path=weight_name, skip=[0,0])
    102     # model.summary()
    103 

/content/model.py in get_model(graph_path, ROI_N, frames, kernels, k, l2_reg, dp, num_classes, weight_path, skip)
    134     # ConvLSTM2D layer for temporal info, bettern than RNN
    135     # L2 reg for recurrent parameters for easy convergence
--> 136     net = ConvLSTM2D(kernels[5], kernel_size=(1,1), padding='same', 
    137                    return_sequences=True, recurrent_regularizer=l2(l2_reg))(net)
    138     net = TimeDistributed(BatchNormalization())(net)

IndexError: list index out of range

Can you please help me fix this error and implement this code on google colab notebook.

**Comment by leowang16** [comment]
Is your kernels a list of integers (more than 6 )?

**Comment by uaadesh** [comment]
I did not make any changes to the code, I just copied most of it and wrote some code to import the dataset on the colab.
I can share the notebook if you want.

**Comment by uaadesh** [comment]
these are the links to my notebooks =>
ABIDE_10_fold   -   https://colab.research.google.com/drive/1ZK_dzmDnwtvRDNs1lyeLzBxdTiC-o-4T?usp=sharing
ABIDE_leave_one_site_out   -   https://colab.research.google.com/drive/1blT9LvY76p6gzkeiT_Xr2zXWSS-8NwL0?usp=sharing

**Comment by leowang16** [comment]
as I mentioned early, your kernels are not like the original one (`kernels: [8, 8, 8, 16, 32, 32]`). plz change accordingly. 

In short, it defines the kernels size for conv layers (`[8, 8, 8, 16, 32]`), rnn layer (`[32]`). otherwise, plz change the model definition accordingly.
